saf:
  broker-url: nio://localhost:61616
  kaha-db-path: /tmp/saf-kaha-db
  user:
    username: foo
    password: bar
  admin:
    username: admin
    password: XERPgYCMUd5b9js

management:
  endpoints.web.exposure.include: health,info,prometheus
  endpoint.health.show-details: ALWAYS
  metrics.enable:
    jvm: false
    tomcat: false
    process: false
    system: false