monitoring-settings:
  polling-frequency-cron-expression: 0,15,30,45 * * * * *
  time-out-for-poll-request-seconds: 5

web-pages:
  - url: https://start.spring.io/
    # no content check
  - url: https://reactjs.org/
    mandatory-content: "painless"
  - url: https://angular.io/
    mandatory-content: "One framework."
  - url: https://www.oracle.com/
    mandatory-content: "make content matching fail"
  - url: https://somerandomnotavailablesite.com/
    mandatory-content: "content does not matter here"